name: Demo Secret Usage

on:
  push:
    branches: [ main ]

jobs:
  show-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Show secret
        run: echo "My secret is ${{ secrets.MY_SECRET }}"

